### ISSUE TITLE
Audio and subtitle track doesn't change

### ISSUE THREAD

**Issue by ahmady2001** [yuroyami/syncplay-mobile#95] opened 2024-04-04 22:36 UTC
Hi. I can't change audio or subtitle of a video in player.
I have tested your app in android 14.
Thanks for your app by the way . I can watch movies with my friends easily.

**Comment by yuroyami** [comment] 2024-04-05 01:21
@ahmady2001 
Its an issue caused by `ExoPlayer` video player. I suggest you use the app variant that contains `mpv` instead as its the recommended and most stable player for now. Refer to #94

TL;DR: From the 0.13.0 release, you will find multiple APKs attached. You're probably using the one that contains only exoplayer (it has "exo-only" in its filename). The other APKs additionally mpv along with exo.

If you prefer Exo nonetheless, the next release will ship out a fix for this track selection issue.

**Comment by ahmady2001** [comment] 2024-04-05 14:10
thanks for the reply. But I installed the version in izzyondroid and it was fine except for this problem that sometimes when I press the enter room button, the program was closed, but when i opened the app again there was no problem (except for the audio track and subtitle track issues).  But now that I have installed the latest version from GitHub (the version that has mpv), when I press the enter room button, the program's closed, and it doesn't matter how many times I repeat it, it will happen again.

**Comment by ahmady2001** [comment] 2024-04-05 14:43
thanks for the reply. But I installed the version in izzyondroid and it was fine except for this problem that sometimes when I press the enter room button, the program was closed, but when i opened the app again there was no problem (except for the audio track and subtitle track issues).  But now that I have installed the latest version from GitHub (the version that has mpv), when I press the enter room button, the program's closed, and it doesn't matter how many times I repeat it, it will happen again.

Update :
I tested the exo only version and it had the same issue. But I installed the 0.12.0 version and it was fine except for some crashes like the crashes that I said the izzyondroid version had (that I think it happens because I don't close the app and when I press the enter room button in my background I sees 2 syncplay apps one in the menu and one in player mode so when I doesn't close player and try to open the app and go to the room it will cause crash) .

**Comment by yuroyami** [comment] 2024-04-06 03:59
@ahmady2001 
Thanks for the feedback. First of all, make sure you uninstall all Syncplay versions before installing a new one; that's because the app is still under heavy development and undergoes a lot of rewriting, which causes incompatibilities and regressions across versions.

Second of all, the second app icon you find in the menu is the shortcut you created (you can create shortcut for your usual room and server by clicking the flag icon button on the home screen, it is right next to the video player engine switch button).

As for the crash, I am not sure what could be causing that, please provide me with your Android phone's model and Android version, and preferably some screen recording to further demonstrate the issue flow.

The track selection issue will be fixed by the next version for sure, which is expected to be this week or the next week. Stay tuned.

**Comment by ahmady2001** [comment] 2024-04-06 12:06
I tested the both versions

0.12.0 version :
https://file.io/HkjuBJRGumo0

0.13.0 version :
https://file.io/GAmxO6VylzvD

I recorded videos from :
Realme gt3
Android 14

**Comment by yuroyami** [comment] 2024-04-13 04:56
@ahmady2001 Try out the [v0.14.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.14.0) version. ExoPlayer should work just fine now, including the track selection. Other players (mpv/VLC) may also work for you.

**Closed** 2024-05-21 20:37 UTC
